In [16]:
import numpy as np
from sklearn.model_selection import cross_val_score
import pandas as pd
from sklearn import neighbors, datasets
from sklearn.model_selection import train_test_split
import matplotlib
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score as accuracy
from sklearn.linear_model import LogisticRegression
from sklearn import metrics

In [17]:
myPatient = pd.read_excel("/Users/nikolai/Downloads/Cryo.xlsx")
myPatient = myPatient.dropna()
print(myPatient)
X = (myPatient.iloc[:,0:6])
y = (myPatient.iloc[:,6:7])
y = np.ravel(y)

    sex  age   Time  Number_of_Warts  Type  Area  Result_of_Treatment
0     1   35  12.00                5     1   100                    0
1     1   29   7.00                5     1    96                    1
2     1   50   8.00                1     3   132                    0
3     1   32  11.75                7     3   750                    0
4     1   67   9.25                1     1    42                    0
5     1   41   8.00                2     2    20                    1
6     1   36  11.00                2     1     8                    0
7     1   59   3.50                3     3    20                    0
8     1   20   4.50               12     1     6                    1
9     2   34  11.25                3     3   150                    0
10    2   21  10.75                5     1    35                    0
11    2   15   6.00                2     1    30                    1
12    2   15   2.00                3     1     4                    1
13    2   15   3.75 

The dataset I am using is concerned with the use and success rate of cryotherapy. The dataset has 90 instances and 7 attributes. The six features I am using represent the sex of the patient(sex), the patient age(age), the time the patient has had a wart(time), the number of warts a patient has(Number_Of_Warts), the type of wart a patient has(type) and lastly the area of the wart(area). The target variable is the result of treatment. 1 means it was treated successfully and 0 means it was not. 

In [18]:
y.mean()

0.5333333333333333

In [19]:
x_train, x_test, y_train, y_test = train_test_split(X, y, test_size = .3)
x_test, x_val, y_test, y_val = train_test_split(x_test, y_test, test_size=0.66)
print(x_train.shape)
print(y_train.shape)
print(x_val.shape)
print(x_test.shape)
print(y_val.shape)
print(y_test.shape)

(63, 6)
(63,)
(18, 6)
(9, 6)
(18,)
(9,)


In [20]:
model2 = LogisticRegression()
model2.fit(x_train, y_train)

predicted = model2.predict(x_test)
print (predicted)

probs = model2.predict_proba(x_test)
print (probs)

[1 1 1 0 0 0 1 0 0]
[[0.26641324 0.73358676]
 [0.28679171 0.71320829]
 [0.09626786 0.90373214]
 [0.98970719 0.01029281]
 [0.89589414 0.10410586]
 [0.90792356 0.09207644]
 [0.0275083  0.9724917 ]
 [0.96619882 0.03380118]
 [0.50819054 0.49180946]]


/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/sklearn/linear_model/logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


In [21]:
 #generate evaluation metrics
#print(probs[:, 1])
#print('Validation:')
#print('Correct answers:')
#print(y_val)
#print('Predicted answers:')
#print(predictedValidation)
print('\n')
print('Testing:')
print('Correct answers: ')
print(y_test)
print('Predicted answers: ')
print(predicted)
print('\n')
print('Test Accuracy Score: ')
print (metrics.accuracy_score(y_test, predicted))
print('\n')
#print (metrics.roc_auc_score(y_test, probs[:, 1]))
thetazero = model2.intercept_
print('Intercept(θ0): ')
print(thetazero)
print('\n')
parameters = model2.coef_
parameters = parameters.tolist()
print('Parameters(θ1, θ2, θ3, θ4, θ5, θ6): ')
print(parameters)



Testing:
Correct answers: 
[1 1 1 0 0 1 1 0 1]
Predicted answers: 
[1 1 1 0 0 0 1 0 0]


Test Accuracy Score: 
0.7777777777777778


Intercept(θ0): 
[2.55050845]


Parameters(θ1, θ2, θ3, θ4, θ5, θ6): 
[[0.7433637893722799, -0.03819202822582429, -0.3942210253866408, 0.2588852692694628, -0.7196870070402678, 0.00046347722160924474]]


The given parameters are the weights associated with each of the features in the data set. We use these coefficents to generate predicted probabilities. We see that an X increase/decrease of θ results in the odds of Y increasing/decreasing by X. We can then convert odds into probability. We see that θ2, θ3, and θ5 are negative values. This means that a higher value in features of 'Type', 'Time', or 'Age' will push the classification of 'Result_Of_Treatment' to 0.